### ISSUE TITLE
Method to clear cookies of the WebBrowser control

### ISSUE THREAD

**Issue by Krutonium** [Odonno/gitter-api-auth#5]
I am having an issue I initially used a bad oauth Redirect URL, (at least I think this is the source of that issue) and I am as a result, unable to actually get a token. and instead the browser control fails to pass the token back to the application.

My working theory as of right now is that a cookie got set in the first session which is causing this issue.
![screenshot 81](https://cloud.githubusercontent.com/assets/3945538/20562261/af17a108-b150-11e6-8cf8-b49e6839935f.png)

**Comment by Odonno** [comment]
I will instead clear cookies on the browser everytime you ask for a token. What do you think ?

**Comment by Odonno** [comment]
It is now done on v0.2.1
